import { Product } from "@/types/product";

const img = (n: number) => ({
  thumbnails: [
    `/images/products/product-${n}-sm-1.png`,
    `/images/products/product-${n}-sm-2.png`,
  ],
  previews: [
    `/images/products/product-${n}-bg-1.png`,
    `/images/products/product-${n}-bg-2.png`,
  ],
});

const shopData: Product[] = [
  {
    id: 1,
    title: "Professional 8-Piece Chef Knife Set",
    slug: "professional-8-piece-chef-knife-set",
    description:
      "High-carbon stainless steel blades with ergonomic handles. Includes chef, santoku, utility, paring, and steak knives plus sharpening steel and block.",
    reviews: 124,
    price: 189.0,
    discountedPrice: 149.0,
    category: "Knives & Cutting",
    brand: "EdgeCraft",
    material: "Stainless steel",
    colors: ["black", "silver"],
    setOptions: [
      { id: "6-piece", title: "6-Piece" },
      { id: "8-piece", title: "8-Piece" },
      { id: "10-piece", title: "10-Piece" },
    ],
    specs: {
      Material: "High-carbon stainless steel",
      "Block material": "Acacia wood",
      Warranty: "Lifetime sharpening",
    },
    imgs: img(1),
  },
  {
    id: 2,
    title: "Japanese Santoku Knife 7-Inch",
    slug: "japanese-santoku-knife-7-inch",
    description:
      "Hollow-ground blade reduces friction for clean slices. Ideal for vegetables, fish, and boneless meats.",
    reviews: 89,
    price: 79.0,
    discountedPrice: 59.0,
    category: "Knives & Cutting",
    brand: "EdgeCraft",
    material: "Damascus steel",
    colors: ["silver"],
    specs: {
      "Blade length": "7 inches",
      Handle: "Pakka wood",
      Weight: "6.2 oz",
    },
    imgs: img(2),
  },
  {
    id: 3,
    title: "Bamboo Cutting Board Set (3-Pack)",
    slug: "bamboo-cutting-board-set",
    description:
      "Eco-friendly bamboo boards in small, medium, and large. Juice grooves on the large board for carving.",
    reviews: 56,
    price: 49.0,
    discountedPrice: 34.0,
    category: "Knives & Cutting",
    brand: "GreenPrep",
    material: "Bamboo",
    colors: ["natural"],
    setOptions: [
      { id: "2-pack", title: "2-Pack" },
      { id: "3-pack", title: "3-Pack" },
    ],
    specs: {
      Material: "Organic bamboo",
      Finish: "Food-safe mineral oil",
      Care: "Hand wash only",
    },
    imgs: img(3),
  },
  {
    id: 4,
    title: "Enameled Cast Iron Dutch Oven 6-Qt",
    slug: "enameled-cast-iron-dutch-oven-6qt",
    description:
      "Heavy-duty Dutch oven for braising, baking bread, and slow cooking. Oven-safe to 500°F with tight-fitting lid.",
    reviews: 203,
    price: 129.0,
    discountedPrice: 99.0,
    category: "Cookware",
    brand: "ForgeKitchen",
    material: "Cast iron",
    colors: ["red", "blue", "cream"],
    specs: {
      Capacity: "6 quarts",
      "Interior coating": "Enameled",
      "Oven safe": "500°F",
    },
    imgs: img(4),
  },
  {
    id: 5,
    title: "Non-Stick Skillet 12-Inch",
    slug: "non-stick-skillet-12-inch",
    description:
      "PFOA-free ceramic non-stick coating. Induction-compatible base with stay-cool handle.",
    reviews: 67,
    price: 59.0,
    discountedPrice: 44.0,
    category: "Cookware",
    brand: "ForgeKitchen",
    material: "Aluminum",
    colors: ["black", "gray"],
    specs: {
      Diameter: "12 inches",
      Coating: "Ceramic non-stick",
      "Dishwasher safe": "Yes",
    },
    imgs: img(5),
  },
  {
    id: 6,
    title: "Stainless Steel Saucepan Set",
    slug: "stainless-steel-saucepan-set",
    description:
      "Tri-ply construction for even heating. Set includes 1.5-qt, 2.5-qt, and 4-qt saucepans with lids.",
    reviews: 41,
    price: 119.0,
    discountedPrice: 89.0,
    category: "Cookware",
    brand: "ForgeKitchen",
    material: "Stainless steel",
    setOptions: [
      { id: "2-piece", title: "2-Piece" },
      { id: "3-piece", title: "3-Piece" },
    ],
    specs: {
      Construction: "Tri-ply",
      "Oven safe": "450°F",
      Lids: "Tempered glass",
    },
    imgs: img(6),
  },
  {
    id: 7,
    title: "Silicone Spatula & Turner Set",
    slug: "silicone-spatula-turner-set",
    description:
      "Heat-resistant to 600°F. Flexible edges for scraping bowls and flipping delicate foods.",
    reviews: 38,
    price: 29.0,
    discountedPrice: 19.0,
    category: "Utensils & Gadgets",
    brand: "PrepPro",
    material: "Silicone",
    colors: ["red", "blue", "gray"],
    setOptions: [
      { id: "4-piece", title: "4-Piece" },
      { id: "6-piece", title: "6-Piece" },
    ],
    specs: {
      "Heat resistant": "600°F",
      "BPA free": "Yes",
      "Dishwasher safe": "Yes",
    },
    imgs: img(7),
  },
  {
    id: 8,
    title: "Stainless Steel Garlic Press",
    slug: "stainless-steel-garlic-press",
    description:
      "Heavy-duty press with ergonomic handles. Easy-clean design with included cleaning tool.",
    reviews: 22,
    price: 24.0,
    discountedPrice: 16.0,
    category: "Utensils & Gadgets",
    brand: "PrepPro",
    material: "Stainless steel",
    colors: ["silver"],
    specs: {
      Material: "18/8 stainless steel",
      "Dishwasher safe": "Yes",
    },
    imgs: img(8),
  },
  {
    id: 9,
    title: "Measuring Cups & Spoons Set",
    slug: "measuring-cups-spoons-set",
    description:
      "Nested cups and spoons with engraved measurements. Magnetic storage strip included.",
    reviews: 51,
    price: 22.0,
    discountedPrice: 15.0,
    category: "Utensils & Gadgets",
    brand: "PrepPro",
    material: "Stainless steel",
    colors: ["silver"],
    specs: {
      Pieces: "12",
      Storage: "Magnetic strip",
      "Dishwasher safe": "Yes",
    },
    imgs: img(1),
  },
  {
    id: 10,
    title: "Wall-Mount Spice Rack (20 Jars)",
    slug: "wall-mount-spice-rack-20-jars",
    description:
      "Space-saving spice organization with pre-labeled glass jars and chalkboard labels.",
    reviews: 73,
    price: 54.0,
    discountedPrice: 42.0,
    category: "Storage",
    brand: "PantryPlus",
    material: "Glass",
    colors: ["clear"],
    specs: {
      Jars: "20 glass jars",
      Mounting: "Wall or counter",
      Labels: "Chalkboard included",
    },
    imgs: img(2),
  },
  {
    id: 11,
    title: "Airtight Food Container Set",
    slug: "airtight-food-container-set",
    description:
      "BPA-free containers with snap-lock lids. Stackable design for pantry and fridge organization.",
    reviews: 94,
    price: 39.0,
    discountedPrice: 29.0,
    category: "Storage",
    brand: "PantryPlus",
    material: "Plastic",
    colors: ["clear"],
    setOptions: [
      { id: "10-piece", title: "10-Piece" },
      { id: "18-piece", title: "18-Piece" },
      { id: "24-piece", title: "24-Piece" },
    ],
    specs: {
      "BPA free": "Yes",
      "Microwave safe": "Lids off",
      Stackable: "Yes",
    },
    imgs: img(3),
  },
  {
    id: 12,
    title: "Electric Kettle 1.7L",
    slug: "electric-kettle-1-7l",
    description:
      "Rapid-boil kettle with auto shut-off and boil-dry protection. Perfect for tea, pour-over coffee, and cooking prep.",
    reviews: 112,
    price: 49.0,
    discountedPrice: 39.0,
    category: "Small Appliances",
    brand: "BrewBase",
    material: "Stainless steel",
    colors: ["silver", "black"],
    specs: {
      Capacity: "1.7 liters",
      Power: "1500W",
      "Auto shut-off": "Yes",
    },
    imgs: img(4),
  },
  {
    id: 13,
    title: "Immersion Hand Blender",
    slug: "immersion-hand-blender",
    description:
      "Variable speed stick blender with whisk and chopper attachments. Ideal for soups, sauces, and smoothies.",
    reviews: 48,
    price: 45.0,
    discountedPrice: 35.0,
    category: "Small Appliances",
    brand: "BrewBase",
    material: "Plastic",
    colors: ["black", "white"],
    specs: {
      Speeds: "8 variable",
      Attachments: "Whisk, chopper",
      Warranty: "2 years",
    },
    imgs: img(5),
  },
  {
    id: 14,
    title: "Half-Sheet Baking Pan (2-Pack)",
    slug: "half-sheet-baking-pan-2-pack",
    description:
      "Commercial-grade aluminum pans with rolled edges. Non-warping design for even baking.",
    reviews: 35,
    price: 28.0,
    discountedPrice: 22.0,
    category: "Bakeware",
    brand: "BakeWell",
    material: "Aluminum",
    colors: ["silver"],
    setOptions: [
      { id: "1-pack", title: "1-Pack" },
      { id: "2-pack", title: "2-Pack" },
    ],
    specs: {
      Size: "18 x 13 inches",
      Material: "Heavy-gauge aluminum",
      "Dishwasher safe": "Yes",
    },
    imgs: img(6),
  },
  {
    id: 15,
    title: "Stainless Mixing Bowl Set",
    slug: "stainless-mixing-bowl-set",
    description:
      "Nested bowls with non-slip bases. Includes 1.5-qt, 3-qt, and 5-qt sizes for prep and serving.",
    reviews: 29,
    price: 42.0,
    discountedPrice: 32.0,
    category: "Bakeware",
    brand: "BakeWell",
    material: "Stainless steel",
    colors: ["silver"],
    setOptions: [
      { id: "3-piece", title: "3-Piece" },
      { id: "5-piece", title: "5-Piece" },
    ],
    specs: {
      Material: "18/8 stainless steel",
      "Non-slip base": "Yes",
      Nesting: "Yes",
    },
    imgs: img(7),
  },
];

export default shopData;
